const authActionTypes={
    REGISTER_SUCCESS:'REGISTER_SUCCESS',
    REGISTER_FAILURE:'REGISTER_FAILURE',
    USER_LOADED: 'USER_LOADED',
    AUTH_ERROR:'AUTH_ERROR',
    LOGIN_SUCCESS:'LOGIN_SUCCESS',
    LOGIN_FAILURE:'LOGIN_FAILURE'
};

export default authActionTypes;